version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: halalhub_db
    environment:
      POSTGRES_USER: halalhub_user
      POSTGRES_PASSWORD: halalhub123
      POSTGRES_DB: halalhub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - halalhub_network

  backend:
    build: ./backend
    container_name: halalhub_backend
    environment:
      - PORT=5000
      - JWT_SECRET=halalhub_sharia_secure_2025
      - NODE_ENV=production
      - DB_USER=halalhub_user
      - DB_PASSWORD=halalhub123
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=halalhub
      - EMAIL_USER=quantivo.itech@gmail.com
      - EMAIL_PASS=ivulhamkhihxzgnp
      - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
      - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
      - MPESA_SHORTCODE=${MPESA_SHORTCODE}
      - MPESA_PASSKEY=${MPESA_PASSKEY}
      - MPESA_CALLBACK_URL=${MPESA_CALLBACK_URL}
      - AT_USERNAME=${AT_USERNAME}
      - AT_API_KEY=${AT_API_KEY}
      - AT_FROM=${AT_FROM}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - halalhub_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: halalhub_frontend
    ports:
      - "9999:80"
    depends_on:
      - backend
    networks:
      - halalhub_network

networks:
  halalhub_network:
    driver: bridge

volumes:
  postgres_data: